FROM golang:1.23-alpine AS dev

RUN go install github.com/air-verse/air@latest \
    && go install github.com/jackc/tern@latest

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

EXPOSE 8000
# air --build.cmd "go build -o ./bin/api ./cmd/api" --build.bin "./bin/api"
CMD ["air", "-c", ".air.toml"]